apiVersion: apps/v1
kind: Deployment
metadata:
  name: primerjalnik-cen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primerjalnik-cen
  template:
    metadata:
      labels:
        app: primerjalnik-cen
    spec:
      containers:
        - image: maticsuc/primerjalnik_cen:2022-12-30-11-05-54
          name: primerjalnik-cen
          env:
            - name: DBHOST
              value: ella.db.elephantsql.com
            - name: DBNAME
              value: rprwteet
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: username
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
          ports:
            - containerPort: 80
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: primerjalnik-cen
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: primerjalnik-cen